/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DesignWindows;

import Company.*;
import DataBase.ReadWriteObject;
import User.Admin;
import User.Client;
import User.Employee;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author suare
 */
public class HeadquarterWindow extends javax.swing.JFrame {

    /**
     * Creates new form HeadquarterWindow
     */
    private static Client[] client;
    private static Admin[] admin;
    private static Employee[] employee;
    private static Company company;
    private static boolean createActive = false;
    private static boolean listActive = false;
    private static ReadWriteObject rwo=new ReadWriteObject(); 
    
    public HeadquarterWindow() {
        initComponents();
    }
    
    public HeadquarterWindow(Client[] myClient,Admin[] myAdmin, Employee[] myEmployee,Company myCompany) {
        initComponents();
        setVisible(true);
        client = myClient;
        admin = myAdmin;
        employee = myEmployee;
        company = myCompany;
        setLocationRelativeTo(null);
        txtSectorName.setEnabled(false);
        txtHeadquarterID.setEnabled(false);
        btnDone.setEnabled(false);
        btnDelete.setEnabled(false);
        lstList.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxCreate = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstList = new javax.swing.JList<>();
        btnDone = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cbxList = new javax.swing.JCheckBox();
        lblHeadquarter = new javax.swing.JLabel();
        txtSectorName = new javax.swing.JTextField();
        txtHeadquarterID = new javax.swing.JTextField();
        lblSectorName = new javax.swing.JLabel();
        lblHeadquarterID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbxCreate.setText("Create");
        cbxCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCreateActionPerformed(evt);
            }
        });

        lstList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstList);
        lstList.getAccessibleContext().setAccessibleName("lstList");

        btnDone.setText("¡Done!");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cbxList.setText("List");
        cbxList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxListActionPerformed(evt);
            }
        });

        lblHeadquarter.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeadquarter.setText("Headquarter");

        txtHeadquarterID.setToolTipText("");

        lblSectorName.setText("Sector Name");

        lblHeadquarterID.setText("Headquarter ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblSectorName)
                                .addGap(18, 18, 18)
                                .addComponent(txtSectorName))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblHeadquarterID)
                                .addGap(18, 18, 18)
                                .addComponent(txtHeadquarterID)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnDone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeadquarter)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbxCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxList)
                        .addGap(28, 28, 28)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeadquarter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCreate)
                    .addComponent(cbxList))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSectorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSectorName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHeadquarterID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHeadquarterID))
                        .addGap(52, 52, 52)
                        .addComponent(btnDone)
                        .addGap(21, 21, 21)))
                .addComponent(btnDelete)
                .addGap(8, 8, 8))
        );

        cbxCreate.getAccessibleContext().setAccessibleName("cbxCreate");
        btnDone.getAccessibleContext().setAccessibleName("btnDone");
        btnDelete.getAccessibleContext().setAccessibleName("btnDelete");
        cbxList.getAccessibleContext().setAccessibleName("cbxList");
        lblHeadquarter.getAccessibleContext().setAccessibleName("lblHeadquarter");
        txtSectorName.getAccessibleContext().setAccessibleName("txtSectorName");
        txtHeadquarterID.getAccessibleContext().setAccessibleName("txtHeadquarterID");
        lblSectorName.getAccessibleContext().setAccessibleName("lblSectorName");
        lblHeadquarterID.getAccessibleContext().setAccessibleName("lblHeadquarterID");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCreateActionPerformed
        if(createActive == false){
            createActive = true;            
        }
        else {
            createActive = false;
        }        
        cbxList.setEnabled(!createActive);
        txtSectorName.setEnabled(createActive);
        txtHeadquarterID.setEnabled(createActive);
        btnDone.setEnabled(createActive);
    }//GEN-LAST:event_cbxCreateActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        Headquarter myHeadquarter = null;
        if(createActive == true){
            if(!txtSectorName.getText().trim().isEmpty() && !txtHeadquarterID.getText().trim().isEmpty()){
                company.addHeadquarters(new Headquarter(txtSectorName.getText().trim(),txtHeadquarterID.getText().trim()));
            }
        }
        else if(listActive == true){
            for (int i=0;i<company.getHeadquartersList().size();i++) {
                if (company.getHeadquartersList().get(i).getSectorName().equalsIgnoreCase(lstList.getSelectedValue())) {
                    myHeadquarter = company.getHeadquartersList().get(i);
                }
            }
            company.editHeadquarters(myHeadquarter, new Headquarter(txtSectorName.getText(), txtHeadquarterID.getText()));
            if(!company.getHeadquartersList().isEmpty()) {
                String[]  list = new String[company.getHeadquartersList().size()];
                list = company.listHeadquarters();
                lstList.setListData(list);
            }
            else {
                lstList.setListData(new String[]{""});
            }
        }
        try {
            rwo.write(new File("Bin","Company.bin"),false, company);
        } catch (IOException ex) {
            Logger.getLogger(HeadquarterWindow.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_btnDoneActionPerformed

    private void cbxListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxListActionPerformed
        if(listActive == false){
            listActive = true; 
            try {
                rwo.read(new File("Bin","Company.bin"), company);
            } catch (IOException ex) {
                Logger.getLogger(HeadquarterWindow.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HeadquarterWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(!company.getHeadquartersList().isEmpty()) {
                String[]  list = new String[company.getHeadquartersList().size()];
                list = company.listHeadquarters();
                lstList.setListData(list);
            }
            else {
                lstList.setListData(new String[]{""});
            }
        }
        else {
            listActive = false;
            lstList.setListData(new String[]{""});
            btnDone.setEnabled(listActive);
            btnDelete.setEnabled(listActive);
            txtSectorName.setEnabled(listActive);
            txtHeadquarterID.setEnabled(listActive);
        }
        cbxCreate.setEnabled(!listActive);
        lstList.setEnabled(listActive);        
    }//GEN-LAST:event_cbxListActionPerformed

    private void lstListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstListMouseClicked
        if(createActive == false) {
        Headquarter myHeadquarter = null;
        btnDone.setEnabled(listActive);
        btnDelete.setEnabled(listActive);
        txtSectorName.setEnabled(listActive);
        txtHeadquarterID.setEnabled(listActive);
        txtSectorName.setText(lstList.getSelectedValue());
        for (int i=0;i<company.getHeadquartersList().size();i++) {
            if (company.getHeadquartersList().get(i).getSectorName().equalsIgnoreCase(lstList.getSelectedValue())) {
                myHeadquarter = company.getHeadquartersList().get(i);
            }
        }
        txtHeadquarterID.setText(myHeadquarter.getIdHeadquarters());
        }
    }//GEN-LAST:event_lstListMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Headquarter myHeadquarter = null;
        for (int i=0;i<company.getHeadquartersList().size();i++) {
            if (company.getHeadquartersList().get(i).getSectorName().equalsIgnoreCase(lstList.getSelectedValue())) {
                myHeadquarter = company.getHeadquartersList().get(i);
            }
        }
        company.deleteHeadquarters(myHeadquarter);
        try {
            rwo.write(new File("Bin","Company.bin"),false, company);
        } catch (IOException ex) {
            Logger.getLogger(HeadquarterWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(!company.getHeadquartersList().isEmpty()) {
                String[]  list = new String[company.getHeadquartersList().size()];
                list = company.listHeadquarters();
                lstList.setListData(list);
            }
            else {
                lstList.setListData(new String[]{""});
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeadquarterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeadquarterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeadquarterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeadquarterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HeadquarterWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDone;
    private javax.swing.JCheckBox cbxCreate;
    private javax.swing.JCheckBox cbxList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeadquarter;
    private javax.swing.JLabel lblHeadquarterID;
    private javax.swing.JLabel lblSectorName;
    private javax.swing.JList<String> lstList;
    private javax.swing.JTextField txtHeadquarterID;
    private javax.swing.JTextField txtSectorName;
    // End of variables declaration//GEN-END:variables
}
