/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DesignWindows;

import Company.*;
import DataBase.ReadWriteObject;
import Product.*;
import User.Admin;
import User.Client;
import User.Employee;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author suare
 */
public class ProductWindow extends javax.swing.JFrame {

    /**
     * Creates new form ProductWindow
     */
    
    private static Client[] client;
    private static Admin[] admin;
    private static Employee[] employee;
    private static Company company;
    private static boolean TechincalActive = false;
    private static boolean listActive = false;
    private static ReadWriteObject rwo=new ReadWriteObject(); 
    private static Headquarter myHeadquarter;
    
    public ProductWindow() {
        initComponents();
    }
    
    public ProductWindow(Client[] myClient,Admin[] myAdmin, Employee[] myEmployee,Company myCompany) {
        initComponents();
        setVisible(true);
        client = myClient;
        admin = myAdmin;
        employee = myEmployee;
        company = myCompany;
        setLocationRelativeTo(null);        
        txtProductName.setEnabled(false);
        txtProductID.setEnabled(false);
        txtTechicianName.setEnabled(false);
        txtTechicianPercentage.setEnabled(false);
        txtPrice.setEnabled(false);
        btnDelete.setEnabled(false);
        btnDone.setEnabled(false);
        for (int i=0;i<myCompany.getHeadquartersList().size();i++) {
                cobxHeadquarter.addItem(myCompany.getHeadquartersList().get(i).getSectorName());
            } 
        for (int i=0;i<company.getHeadquartersList().size();i++) {
            if (company.getHeadquartersList().get(i).getSectorName().equalsIgnoreCase((String)cobxHeadquarter.getSelectedItem())) {
                myHeadquarter = company.getHeadquartersList().get(i);
            }
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtProductName = new javax.swing.JTextField();
        txtProductID = new javax.swing.JTextField();
        lblProductName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstList = new javax.swing.JList<>();
        lblProductID = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblHeadquarter = new javax.swing.JLabel();
        cbxList = new javax.swing.JCheckBox();
        cobxHeadquarter = new javax.swing.JComboBox<>();
        lblProduct = new javax.swing.JLabel();
        cbxTechincalService = new javax.swing.JCheckBox();
        txtTechicianName = new javax.swing.JTextField();
        txtTechicianPercentage = new javax.swing.JTextField();
        lblTechicianName = new javax.swing.JLabel();
        lblTecnicPercentage = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblProductName1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtProductID.setToolTipText("");

        lblProductName.setText("Product Name");

        lstList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstList);
        lstList.getAccessibleContext().setAccessibleName("lstList");

        lblProductID.setText("Product ID");

        btnDone.setText("¡Done!");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblHeadquarter.setText("Headquarter");

        cbxList.setText("List");
        cbxList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxListActionPerformed(evt);
            }
        });

        cobxHeadquarter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobxHeadquarterActionPerformed(evt);
            }
        });

        lblProduct.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblProduct.setText("Product");

        cbxTechincalService.setText("Techincal Service");
        cbxTechincalService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTechincalServiceActionPerformed(evt);
            }
        });

        txtTechicianPercentage.setToolTipText("");

        lblTechicianName.setText("Techician Name");

        lblTecnicPercentage.setText("Tecnic Percentage");

        lblProductName1.setText("Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHeadquarter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cobxHeadquarter, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTechicianName)
                                    .addComponent(lblTecnicPercentage)
                                    .addComponent(lblProductID)
                                    .addComponent(lblProductName)
                                    .addComponent(lblProductName1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtProductID)
                                    .addComponent(txtProductName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTechicianName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTechicianPercentage)
                                    .addComponent(txtPrice))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(cbxTechincalService)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbxList)
                                    .addComponent(lblProduct))
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDone)
                                .addGap(105, 105, 105)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cobxHeadquarter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeadquarter))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxList)
                            .addComponent(cbxTechincalService))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductName1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductID))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTechicianName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTechicianName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTechicianPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTecnicPercentage))
                        .addGap(21, 21, 21)
                        .addComponent(btnDone)))
                .addGap(8, 8, 8))
        );

        txtProductName.getAccessibleContext().setAccessibleName("txtProductName");
        txtProductName.getAccessibleContext().setAccessibleDescription("");
        txtProductID.getAccessibleContext().setAccessibleName("txtProductID");
        lblProductName.getAccessibleContext().setAccessibleName("lblProductName");
        lblProductID.getAccessibleContext().setAccessibleName("lblProductID");
        btnDone.getAccessibleContext().setAccessibleName("btnDone");
        btnDelete.getAccessibleContext().setAccessibleName("btnDelete");
        lblHeadquarter.getAccessibleContext().setAccessibleName("lblHeadquarter");
        cbxList.getAccessibleContext().setAccessibleName("cbxList");
        cobxHeadquarter.getAccessibleContext().setAccessibleName("cobxHeadquarter");
        lblProduct.getAccessibleContext().setAccessibleName("lblProduct");
        cbxTechincalService.getAccessibleContext().setAccessibleName("cbxTechincalService");
        txtTechicianName.getAccessibleContext().setAccessibleName("txtTechicianName");
        txtTechicianPercentage.getAccessibleContext().setAccessibleName("txtTechicianPercentage");
        lblTechicianName.getAccessibleContext().setAccessibleName("lblTechicianName");
        lblTechicianName.getAccessibleContext().setAccessibleDescription("");
        lblTecnicPercentage.getAccessibleContext().setAccessibleName("lblTecnicPercentage");
        txtPrice.getAccessibleContext().setAccessibleName("txtPrice");
        lblProductName1.getAccessibleContext().setAccessibleName("lblPrice");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        Product myProduct = null;
        Reference myReference = null;
        if(TechincalActive == true){
            if(!txtTechicianName.getText().trim().isEmpty() && !txtTechicianPercentage.getText().trim().isEmpty()){
                myHeadquarter.getStock().addPoduct(new TechnicalService(txtTechicianName.getText().trim(),Integer.parseInt(txtTechicianPercentage.getText().trim()), txtProductName.getText().trim(), Integer.parseInt(txtPrice.getText().trim()), Integer.parseInt(txtProductID.getText().trim()),true));
            }
        }
        else if(listActive == true){
            for (int i=0;i<myHeadquarter.getStock().getProductList().size();i++) {
                if (myHeadquarter.getStock().getProductList().get(i).getProductName().equalsIgnoreCase(lstList.getSelectedValue())) {
                    myProduct = myHeadquarter.getStock().getProductList().get(i);
                }
            }
            if(myProduct.getIsTechnical() == false) { 
                myReference = (Reference) myProduct;
                myHeadquarter.getStock().editProduct(myReference,new Reference(myReference.getNameReference(),myReference.getIdReference(),myReference.getAmount(),myReference.getBrandName(),myReference.getIdBrand(),txtProductName.getText(),myReference.getPrice(),Integer.parseInt(txtProductID.getText()),myReference.getIsTechnical()));
            }
            else {
                myHeadquarter.getStock().editProduct(myProduct,new TechnicalService(txtTechicianName.getText(), Integer.parseInt(txtTechicianPercentage.getText()), txtProductName.getText(), Integer.parseInt(txtPrice.getText()), Integer.parseInt(txtProductID.getText()), true));
            }
            if(!company.getHeadquartersList().isEmpty()) {
                if (!myHeadquarter.getStock().getProductList().isEmpty()) {
                    String[]  list = new String[myHeadquarter.getStock().getProductList().size()];
                    list = myHeadquarter.getStock().listProduct();
                    lstList.setListData(list);
                }
            }
            else {
                lstList.setListData(new String[]{""});
            }
        }
        try {
            rwo.write(new File("Bin","Company.bin"),false, company);
        } catch (IOException ex) {
            Logger.getLogger(HeadquarterWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDoneActionPerformed

    private void cbxTechincalServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTechincalServiceActionPerformed
        if(TechincalActive == false){
            TechincalActive = true;            
        }
        else {
            TechincalActive = false;
        }        
        cbxList.setEnabled(!TechincalActive);
        txtTechicianName.setEnabled(TechincalActive);
        txtTechicianPercentage.setEnabled(TechincalActive);
        txtProductID.setEnabled(TechincalActive);
        txtProductName.setEnabled(TechincalActive);
        txtPrice.setEnabled(TechincalActive);
        btnDone.setEnabled(TechincalActive);
    }//GEN-LAST:event_cbxTechincalServiceActionPerformed

    private void cobxHeadquarterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobxHeadquarterActionPerformed
        for (int i=0;i<company.getHeadquartersList().size();i++) {
            if (company.getHeadquartersList().get(i).getSectorName().equalsIgnoreCase((String)cobxHeadquarter.getSelectedItem())) {
                myHeadquarter = company.getHeadquartersList().get(i);
            }
        }
    }//GEN-LAST:event_cobxHeadquarterActionPerformed

    private void cbxListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxListActionPerformed
        if(listActive == false){
            listActive = true; 
            try {
                rwo.read(new File("Bin","Company.bin"), company);
            } catch (IOException ex) {
                Logger.getLogger(HeadquarterWindow.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HeadquarterWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(!company.getHeadquartersList().isEmpty()) {
                if (!myHeadquarter.getStock().getProductList().isEmpty()) {
                    String[]  list = new String[myHeadquarter.getStock().getProductList().size()];
                    list = myHeadquarter.getStock().listProduct();
                    lstList.setListData(list);
                }
            }
            else {
                lstList.setListData(new String[]{""});
            }
        }
        else {
            listActive = false;
            txtPrice.setEnabled(listActive);
            txtTechicianName.setEnabled(listActive);
            txtTechicianPercentage.setEnabled(listActive);  
            txtProductID.setEnabled(listActive);
            txtProductName.setEnabled(listActive); 
            lstList.setListData(new String[]{""});
            btnDone.setEnabled(listActive);
            btnDelete.setEnabled(listActive);            
        }
        cbxTechincalService.setEnabled(!listActive);
        lstList.setEnabled(listActive);
    }//GEN-LAST:event_cbxListActionPerformed

    private void lstListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstListMouseClicked
        Product myProduct = null;
        TechnicalService myTechnicalService = null;
        for (int i=0;i<myHeadquarter.getStock().getProductList().size();i++) {
            if (myHeadquarter.getStock().getProductList().get(i).getProductName().equalsIgnoreCase(lstList.getSelectedValue())) {
                myProduct = myHeadquarter.getStock().getProductList().get(i);
            }
        }
        if(myProduct.getIsTechnical()) {
            myTechnicalService = (TechnicalService) myProduct;
            txtPrice.setEnabled(listActive);
            txtTechicianName.setEnabled(listActive);
            txtTechicianPercentage.setEnabled(listActive);
            txtPrice.setText(String.valueOf(myTechnicalService.getPrice()));
            txtProductName.setText(myTechnicalService.getProductName());
            txtProductID.setText(String.valueOf(myTechnicalService.getIdProduct()));
            txtTechicianName.setText(myTechnicalService.getTechnicianName());
            txtTechicianPercentage.setText(String.valueOf(myTechnicalService.getTecnicPercentage()));            
        }
        else {
            txtPrice.setEnabled(!listActive);
            txtTechicianName.setEnabled(!listActive);
            txtTechicianPercentage.setEnabled(!listActive);
            txtProductName.setText(myProduct.getProductName());
            txtProductID.setText(String.valueOf(myProduct.getIdProduct()));
        }   
        txtProductID.setEnabled(listActive);
        txtProductName.setEnabled(listActive);
        btnDone.setEnabled(listActive);
        btnDelete.setEnabled(listActive);
        
    }//GEN-LAST:event_lstListMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Product myProduct = null;
        for (int i=0;i<myHeadquarter.getStock().getProductList().size();i++) {
            if (myHeadquarter.getStock().getProductList().get(i).getProductName().equalsIgnoreCase(lstList.getSelectedValue())) {
                myProduct = myHeadquarter.getStock().getProductList().get(i);
            }
        }
        myHeadquarter.getStock().deleteProduct(myProduct);
        if(!company.getHeadquartersList().isEmpty()) {
                if (!myHeadquarter.getStock().getProductList().isEmpty()) {
                    String[]  list = new String[myHeadquarter.getStock().getProductList().size()];
                    list = myHeadquarter.getStock().listProduct();
                    lstList.setListData(list);
                }
            }
            else {
                lstList.setListData(new String[]{""});
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDone;
    private javax.swing.JCheckBox cbxList;
    private javax.swing.JCheckBox cbxTechincalService;
    private javax.swing.JComboBox<String> cobxHeadquarter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeadquarter;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblProductID;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductName1;
    private javax.swing.JLabel lblTechicianName;
    private javax.swing.JLabel lblTecnicPercentage;
    private javax.swing.JList<String> lstList;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtTechicianName;
    private javax.swing.JTextField txtTechicianPercentage;
    // End of variables declaration//GEN-END:variables
}
